name: checkout

on: [push]

jobs:

  checkout:
    runs-on: ubuntu-latest
    steps:
      - name : checkout
        uses : actions/checkout@v3
      - run : echo ${GITHUB_REF##*/}
      - run : du -skh --exclude=".git"